apiVersion: v1
kind: Service
metadata:
  name: springboot-crud-svc
spec:
  type: NodePort
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
